### ISSUE TITLE
Error: calculating next Solar term

### ISSUE THREAD

**Issue by luc-nham** [luc-nham/lunar-calendar#89]
### Description
When the current term is Awakening of Insects (longitude 345), the expected grade is Spring Equinox (longitude 0) for the current input year, but the result returns term for the previous year. Errors do not appear every year.

### Example input
- Target class: `SolarTerm`
- Date: 2025-03-05 23:59:59
- Current term: Awakening of Insects
- Expected next term: Spring Equinox of 2025
- Actual term: Spring Equinox of 2024

code: `new SolarTerm(new DateTime('2025-03-05 23:59:59'))->next()`

**Comment by naujienos** [comment]
Hi, thanks for the project!
Is it possible to adapt your PHP lunar calendar script to work with the Buddhist calendar (with BE year numbering and Theravada lunar rules)? Could you share your Facebook or another contact platform for further discussion?
